### ISSUE TITLE
'Glacial Split' Range?

### ISSUE THREAD

**Issue by Demaar** [Shiriow/EOXOA#1]
In the Sim, the description of Glacial Split is not quite clear on if the INT-based Ice follow-up is ranged like with Zephyr Stride or melee.
For that matter, were any weapon ranges changed by this mod?
I always thought that spears should not have backrow penalties, aka function like they did back in EO3.

**Comment by Shiriow** [comment]
My bad, the follow up is also ranged.
The only weapon range that got changed were Knives due to Nightseeker's gimmick.
For whatever reason weapon range is pretty hardcoded and last time we changed knives it broke a lot of things so I'd rather not touch it ever again
